import type { ExerciseMotionData, Pose } from "./types";

/**
 * Hand-authored keyframe data for the flagship exercise set. Each
 * entry is a simplified, directionally-correct schematic (not
 * motion-captured biomechanics) — its job is to teach the shape of
 * the movement, not to be forensically precise. Two or three phases
 * per exercise; the player ping-pongs forward then back through them
 * so the loop reads as one continuous repetition.
 *
 * Every id here is deliberately also a valid `animationId` value on
 * `LOCAL_EXERCISE_LIBRARY` (lib/workouts/exercise-library.ts). Any
 * exercise WITHOUT a matching id here has no `animationId` set and
 * the UI must fall back to "Technique animation coming soon" rather
 * than guessing at motion data — see components/training/exercise-technique-panel.tsx.
 */

const VIEW_BOX = "0 0 120 160";

function pose(p: Pose): Pose {
  return p;
}

const benchPress: ExerciseMotionData = {
  id: "bench-press",
  name: "Barbell Bench Press",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Bar at chest",
      pose: pose({
        head: { x: 78, y: 88 },
        neck: { x: 66, y: 90 },
        shoulderL: { x: 58, y: 84 },
        shoulderR: { x: 58, y: 96 },
        elbowL: { x: 46, y: 70 },
        elbowR: { x: 46, y: 110 },
        wristL: { x: 58, y: 84 },
        wristR: { x: 58, y: 96 },
        hipL: { x: 30, y: 87 },
        hipR: { x: 30, y: 93 },
        kneeL: { x: 18, y: 72 },
        kneeR: { x: 18, y: 108 },
        ankleL: { x: 10, y: 92 },
        ankleR: { x: 10, y: 104 },
      }),
    },
    {
      id: "lockout",
      label: "Lockout",
      pose: pose({
        head: { x: 78, y: 88 },
        neck: { x: 66, y: 90 },
        shoulderL: { x: 58, y: 84 },
        shoulderR: { x: 58, y: 96 },
        elbowL: { x: 54, y: 70 },
        elbowR: { x: 54, y: 110 },
        wristL: { x: 50, y: 55 },
        wristR: { x: 50, y: 60 },
        hipL: { x: 30, y: 87 },
        hipR: { x: 30, y: 93 },
        kneeL: { x: 18, y: 72 },
        kneeR: { x: 18, y: 108 },
        ankleL: { x: 10, y: 92 },
        ankleR: { x: 10, y: 104 },
      }),
    },
  ],
};

const chestPress: ExerciseMotionData = {
  id: "chest-press",
  name: "Machine Chest Press",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Handles at chest",
      pose: pose({
        head: { x: 62, y: 18 },
        neck: { x: 60, y: 28 },
        shoulderL: { x: 56, y: 32 },
        shoulderR: { x: 64, y: 34 },
        elbowL: { x: 42, y: 40 },
        elbowR: { x: 46, y: 46 },
        wristL: { x: 58, y: 34 },
        wristR: { x: 64, y: 38 },
        hipL: { x: 58, y: 88 },
        hipR: { x: 62, y: 90 },
        kneeL: { x: 40, y: 108 },
        kneeR: { x: 42, y: 112 },
        ankleL: { x: 40, y: 140 },
        ankleR: { x: 42, y: 142 },
      }),
    },
    {
      id: "extend",
      label: "Arms extended",
      pose: pose({
        head: { x: 62, y: 18 },
        neck: { x: 60, y: 28 },
        shoulderL: { x: 56, y: 32 },
        shoulderR: { x: 64, y: 34 },
        elbowL: { x: 34, y: 30 },
        elbowR: { x: 38, y: 34 },
        wristL: { x: 20, y: 28 },
        wristR: { x: 22, y: 32 },
        hipL: { x: 58, y: 88 },
        hipR: { x: 62, y: 90 },
        kneeL: { x: 40, y: 108 },
        kneeR: { x: 42, y: 112 },
        ankleL: { x: 40, y: 140 },
        ankleR: { x: 42, y: 142 },
      }),
    },
  ],
};

const latPulldown: ExerciseMotionData = {
  id: "lat-pulldown",
  name: "Lat Pulldown",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Arms extended overhead",
      pose: pose({
        head: { x: 62, y: 22 },
        neck: { x: 60, y: 32 },
        shoulderL: { x: 56, y: 36 },
        shoulderR: { x: 64, y: 38 },
        elbowL: { x: 50, y: 16 },
        elbowR: { x: 54, y: 18 },
        wristL: { x: 46, y: 4 },
        wristR: { x: 50, y: 6 },
        hipL: { x: 58, y: 88 },
        hipR: { x: 62, y: 90 },
        kneeL: { x: 56, y: 116 },
        kneeR: { x: 60, y: 118 },
        ankleL: { x: 54, y: 146 },
        ankleR: { x: 58, y: 148 },
      }),
    },
    {
      id: "pulldown",
      label: "Bar pulled to chest",
      pose: pose({
        head: { x: 62, y: 22 },
        neck: { x: 60, y: 32 },
        shoulderL: { x: 56, y: 36 },
        shoulderR: { x: 64, y: 38 },
        elbowL: { x: 44, y: 42 },
        elbowR: { x: 48, y: 46 },
        wristL: { x: 60, y: 40 },
        wristR: { x: 66, y: 42 },
        hipL: { x: 58, y: 88 },
        hipR: { x: 62, y: 90 },
        kneeL: { x: 56, y: 116 },
        kneeR: { x: 60, y: 118 },
        ankleL: { x: 54, y: 146 },
        ankleR: { x: 58, y: 148 },
      }),
    },
  ],
};

const seatedCableRow: ExerciseMotionData = {
  id: "seated-cable-row",
  name: "Seated Cable Row",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Arms extended forward",
      pose: pose({
        head: { x: 40, y: 22 },
        neck: { x: 44, y: 32 },
        shoulderL: { x: 46, y: 36 },
        shoulderR: { x: 50, y: 38 },
        elbowL: { x: 30, y: 42 },
        elbowR: { x: 34, y: 44 },
        wristL: { x: 12, y: 44 },
        wristR: { x: 14, y: 46 },
        hipL: { x: 56, y: 90 },
        hipR: { x: 60, y: 92 },
        kneeL: { x: 30, y: 92 },
        kneeR: { x: 32, y: 96 },
        ankleL: { x: 12, y: 100 },
        ankleR: { x: 14, y: 104 },
      }),
    },
    {
      id: "row",
      label: "Handle at torso",
      pose: pose({
        head: { x: 46, y: 20 },
        neck: { x: 48, y: 30 },
        shoulderL: { x: 48, y: 34 },
        shoulderR: { x: 52, y: 36 },
        elbowL: { x: 34, y: 46 },
        elbowR: { x: 38, y: 50 },
        wristL: { x: 52, y: 48 },
        wristR: { x: 56, y: 50 },
        hipL: { x: 56, y: 90 },
        hipR: { x: 60, y: 92 },
        kneeL: { x: 30, y: 92 },
        kneeR: { x: 32, y: 96 },
        ankleL: { x: 12, y: 100 },
        ankleR: { x: 14, y: 104 },
      }),
    },
  ],
};

const squat: ExerciseMotionData = {
  id: "squat",
  name: "Barbell Back Squat",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "top",
      label: "Standing",
      pose: pose({
        head: { x: 60, y: 14 },
        neck: { x: 60, y: 24 },
        shoulderL: { x: 55, y: 28 },
        shoulderR: { x: 65, y: 28 },
        elbowL: { x: 50, y: 44 },
        elbowR: { x: 70, y: 44 },
        wristL: { x: 52, y: 58 },
        wristR: { x: 68, y: 58 },
        hipL: { x: 56, y: 84 },
        hipR: { x: 64, y: 84 },
        kneeL: { x: 55, y: 116 },
        kneeR: { x: 65, y: 116 },
        ankleL: { x: 54, y: 148 },
        ankleR: { x: 66, y: 148 },
      }),
    },
    {
      id: "bottom",
      label: "Bottom of squat",
      pose: pose({
        head: { x: 62, y: 46 },
        neck: { x: 62, y: 56 },
        shoulderL: { x: 56, y: 60 },
        shoulderR: { x: 68, y: 60 },
        elbowL: { x: 50, y: 74 },
        elbowR: { x: 74, y: 74 },
        wristL: { x: 52, y: 86 },
        wristR: { x: 72, y: 86 },
        hipL: { x: 52, y: 104 },
        hipR: { x: 68, y: 104 },
        kneeL: { x: 44, y: 122 },
        kneeR: { x: 76, y: 122 },
        ankleL: { x: 50, y: 148 },
        ankleR: { x: 70, y: 148 },
      }),
    },
  ],
};

const legPress: ExerciseMotionData = {
  id: "leg-press",
  name: "Leg Press",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Knees bent",
      pose: pose({
        head: { x: 22, y: 60 },
        neck: { x: 30, y: 62 },
        shoulderL: { x: 32, y: 66 },
        shoulderR: { x: 36, y: 70 },
        elbowL: { x: 34, y: 80 },
        elbowR: { x: 38, y: 84 },
        wristL: { x: 40, y: 90 },
        wristR: { x: 44, y: 94 },
        hipL: { x: 40, y: 92 },
        hipR: { x: 44, y: 96 },
        kneeL: { x: 58, y: 78 },
        kneeR: { x: 62, y: 82 },
        ankleL: { x: 84, y: 88 },
        ankleR: { x: 86, y: 92 },
      }),
    },
    {
      id: "extend",
      label: "Legs extended",
      pose: pose({
        head: { x: 22, y: 60 },
        neck: { x: 30, y: 62 },
        shoulderL: { x: 32, y: 66 },
        shoulderR: { x: 36, y: 70 },
        elbowL: { x: 34, y: 80 },
        elbowR: { x: 38, y: 84 },
        wristL: { x: 40, y: 90 },
        wristR: { x: 44, y: 94 },
        hipL: { x: 40, y: 92 },
        hipR: { x: 44, y: 96 },
        kneeL: { x: 76, y: 90 },
        kneeR: { x: 80, y: 94 },
        ankleL: { x: 108, y: 92 },
        ankleR: { x: 110, y: 96 },
      }),
    },
  ],
};

const romanianDeadlift: ExerciseMotionData = {
  id: "romanian-deadlift",
  name: "Romanian Deadlift",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "top",
      label: "Standing, hips through",
      pose: pose({
        head: { x: 62, y: 14 },
        neck: { x: 62, y: 24 },
        shoulderL: { x: 57, y: 28 },
        shoulderR: { x: 67, y: 28 },
        elbowL: { x: 55, y: 46 },
        elbowR: { x: 69, y: 46 },
        wristL: { x: 54, y: 64 },
        wristR: { x: 70, y: 64 },
        hipL: { x: 58, y: 86 },
        hipR: { x: 66, y: 86 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 66, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 67, y: 148 },
      }),
    },
    {
      id: "hinge",
      label: "Hips hinged back",
      pose: pose({
        head: { x: 44, y: 42 },
        neck: { x: 50, y: 48 },
        shoulderL: { x: 48, y: 52 },
        shoulderR: { x: 60, y: 52 },
        elbowL: { x: 46, y: 70 },
        elbowR: { x: 58, y: 70 },
        wristL: { x: 44, y: 92 },
        wristR: { x: 56, y: 92 },
        hipL: { x: 62, y: 88 },
        hipR: { x: 70, y: 88 },
        kneeL: { x: 58, y: 118 },
        kneeR: { x: 68, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 67, y: 148 },
      }),
    },
  ],
};

const shoulderPress: ExerciseMotionData = {
  id: "shoulder-press",
  name: "Barbell Overhead Press",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Bar at shoulders",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 48, y: 44 },
        elbowR: { x: 72, y: 44 },
        wristL: { x: 56, y: 30 },
        wristR: { x: 64, y: 30 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
    {
      id: "lockout",
      label: "Bar overhead",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 54, y: 12 },
        elbowR: { x: 66, y: 12 },
        wristL: { x: 55, y: -2 },
        wristR: { x: 65, y: -2 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
  ],
};

const lateralRaise: ExerciseMotionData = {
  id: "lateral-raise",
  name: "Cable Lateral Raise",
  view: "frontal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Arms at sides",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 28 },
        shoulderL: { x: 46, y: 32 },
        shoulderR: { x: 74, y: 32 },
        elbowL: { x: 40, y: 54 },
        elbowR: { x: 80, y: 54 },
        wristL: { x: 36, y: 74 },
        wristR: { x: 84, y: 74 },
        hipL: { x: 52, y: 88 },
        hipR: { x: 68, y: 88 },
        kneeL: { x: 51, y: 118 },
        kneeR: { x: 69, y: 118 },
        ankleL: { x: 50, y: 148 },
        ankleR: { x: 70, y: 148 },
      }),
    },
    {
      id: "raised",
      label: "Arms at shoulder height",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 28 },
        shoulderL: { x: 46, y: 32 },
        shoulderR: { x: 74, y: 32 },
        elbowL: { x: 26, y: 30 },
        elbowR: { x: 94, y: 30 },
        wristL: { x: 8, y: 30 },
        wristR: { x: 112, y: 30 },
        hipL: { x: 52, y: 88 },
        hipR: { x: 68, y: 88 },
        kneeL: { x: 51, y: 118 },
        kneeR: { x: 69, y: 118 },
        ankleL: { x: 50, y: 148 },
        ankleR: { x: 70, y: 148 },
      }),
    },
  ],
};

const bicepsCurl: ExerciseMotionData = {
  id: "biceps-curl",
  name: "EZ-Bar Curl",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Arms extended",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 52, y: 52 },
        elbowR: { x: 68, y: 52 },
        wristL: { x: 50, y: 74 },
        wristR: { x: 70, y: 74 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
    {
      id: "curl",
      label: "Peak contraction",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 52, y: 52 },
        elbowR: { x: 68, y: 52 },
        wristL: { x: 44, y: 34 },
        wristR: { x: 76, y: 34 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
  ],
};

const tricepsPushdown: ExerciseMotionData = {
  id: "triceps-pushdown",
  name: "Cable Triceps Pushdown",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "start",
      label: "Elbows bent",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 56, y: 48 },
        elbowR: { x: 66, y: 48 },
        wristL: { x: 50, y: 34 },
        wristR: { x: 72, y: 34 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
    {
      id: "extend",
      label: "Elbows extended",
      pose: pose({
        head: { x: 60, y: 16 },
        neck: { x: 60, y: 26 },
        shoulderL: { x: 55, y: 30 },
        shoulderR: { x: 65, y: 30 },
        elbowL: { x: 56, y: 48 },
        elbowR: { x: 66, y: 48 },
        wristL: { x: 54, y: 70 },
        wristR: { x: 68, y: 70 },
        hipL: { x: 57, y: 88 },
        hipR: { x: 63, y: 88 },
        kneeL: { x: 56, y: 118 },
        kneeR: { x: 64, y: 118 },
        ankleL: { x: 55, y: 148 },
        ankleR: { x: 65, y: 148 },
      }),
    },
  ],
};

const pushUp: ExerciseMotionData = {
  id: "push-up",
  name: "Push-Up",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "top",
      label: "Arms extended",
      pose: pose({
        head: { x: 100, y: 60 },
        neck: { x: 88, y: 62 },
        shoulderL: { x: 82, y: 64 },
        shoulderR: { x: 84, y: 68 },
        elbowL: { x: 80, y: 80 },
        elbowR: { x: 82, y: 84 },
        wristL: { x: 78, y: 96 },
        wristR: { x: 80, y: 100 },
        hipL: { x: 50, y: 68 },
        hipR: { x: 50, y: 72 },
        kneeL: { x: 22, y: 78 },
        kneeR: { x: 22, y: 82 },
        ankleL: { x: 8, y: 90 },
        ankleR: { x: 8, y: 94 },
      }),
    },
    {
      id: "bottom",
      label: "Chest lowered",
      pose: pose({
        head: { x: 100, y: 76 },
        neck: { x: 88, y: 78 },
        shoulderL: { x: 82, y: 80 },
        shoulderR: { x: 84, y: 84 },
        elbowL: { x: 84, y: 88 },
        elbowR: { x: 86, y: 92 },
        wristL: { x: 78, y: 96 },
        wristR: { x: 80, y: 100 },
        hipL: { x: 50, y: 80 },
        hipR: { x: 50, y: 84 },
        kneeL: { x: 22, y: 84 },
        kneeR: { x: 22, y: 88 },
        ankleL: { x: 8, y: 90 },
        ankleR: { x: 8, y: 94 },
      }),
    },
  ],
};

const plank: ExerciseMotionData = {
  id: "plank",
  name: "Plank",
  view: "sagittal",
  viewBox: VIEW_BOX,
  phases: [
    {
      id: "hold-a",
      label: "Braced hold",
      pose: pose({
        head: { x: 100, y: 62 },
        neck: { x: 88, y: 63 },
        shoulderL: { x: 82, y: 64 },
        shoulderR: { x: 84, y: 68 },
        elbowL: { x: 80, y: 82 },
        elbowR: { x: 82, y: 86 },
        wristL: { x: 78, y: 96 },
        wristR: { x: 80, y: 100 },
        hipL: { x: 50, y: 66 },
        hipR: { x: 50, y: 70 },
        kneeL: { x: 22, y: 76 },
        kneeR: { x: 22, y: 80 },
        ankleL: { x: 8, y: 88 },
        ankleR: { x: 8, y: 92 },
      }),
    },
    {
      id: "hold-b",
      label: "Braced hold",
      pose: pose({
        head: { x: 100, y: 62 },
        neck: { x: 88, y: 63 },
        shoulderL: { x: 82, y: 64 },
        shoulderR: { x: 84, y: 68 },
        elbowL: { x: 80, y: 82 },
        elbowR: { x: 82, y: 86 },
        wristL: { x: 78, y: 96 },
        wristR: { x: 80, y: 100 },
        hipL: { x: 50, y: 65.5 },
        hipR: { x: 50, y: 69.5 },
        kneeL: { x: 22, y: 76 },
        kneeR: { x: 22, y: 80 },
        ankleL: { x: 8, y: 88 },
        ankleR: { x: 8, y: 92 },
      }),
    },
  ],
};

export const EXERCISE_MOTION_LIBRARY: Record<string, ExerciseMotionData> = {
  "bench-press": benchPress,
  "chest-press": chestPress,
  "lat-pulldown": latPulldown,
  "seated-cable-row": seatedCableRow,
  squat,
  "leg-press": legPress,
  "romanian-deadlift": romanianDeadlift,
  "shoulder-press": shoulderPress,
  "lateral-raise": lateralRaise,
  "biceps-curl": bicepsCurl,
  "triceps-pushdown": tricepsPushdown,
  "push-up": pushUp,
  plank,
};

export function getExerciseMotion(animationId: string | null | undefined): ExerciseMotionData | null {
  if (!animationId) return null;
  return EXERCISE_MOTION_LIBRARY[animationId] ?? null;
}
