import { NextResponse } from "next/server"

import { z } from "zod"

import { createClient } from "@/lib/supabase/server"
import { computeRecoveryScore } from "@/lib/recovery/score"
import type { RecoveryCheckinRow } from "@/lib/recovery/types"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

const scaleField = z.number().int().min(1).max(10).nullable().optional()

const checkinSchema = z.object({
  sleepHours: z.number().min(0).max(24).nullable().optional(),
  sleepQuality: scaleField,
  stress: scaleField,
  fatigue: scaleField,
  soreness: scaleField,
  mood: scaleField,
  readiness: scaleField,
  restingHr: z.number().int().min(25).max(220).nullable().optional(),
  steps: z.number().int().min(0).nullable().optional(),
  painIllness: z.enum(["no", "minor", "yes"]).default("no"),
  notes: z.string().max(600).nullable().optional(),
})

function todayIso(): string {
  return new Date().toISOString().slice(0, 10)
}

export async function POST(request: Request) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  let body: unknown

  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: "Invalid JSON." }, { status: 400 })
  }

  const parsed = checkinSchema.safeParse(body)

  if (!parsed.success) {
    return NextResponse.json(
      {
        error: "Invalid check-in data.",
        details: parsed.error.flatten(),
      },
      { status: 400 },
    )
  }

  const input = parsed.data

  /* -----------------------------------------------------
     LOAD RECENT HISTORY FOR THE BASELINE COMPARISON
  ----------------------------------------------------- */

  const { data: historyRows, error: historyError } = await supabase
    .from("recovery_checkins")
    .select("checkin_date, recovery_score")
    .eq("user_id", user.id)
    .neq("checkin_date", todayIso())
    .order("checkin_date", { ascending: false })
    .limit(30)

  if (historyError) {
    console.warn("[RECOVERY CHECKIN] history load failed:", historyError.message)
  }

  const history = (historyRows ?? []).map((row) => ({
    score: row.recovery_score as number | null,
  }))

  /* -----------------------------------------------------
     DETERMINISTIC SCORE — never generated by Groq
  ----------------------------------------------------- */

  const result = computeRecoveryScore(
    {
      sleepHours: input.sleepHours ?? null,
      sleepQuality: input.sleepQuality ?? null,
      stress: input.stress ?? null,
      fatigue: input.fatigue ?? null,
      soreness: input.soreness ?? null,
      mood: input.mood ?? null,
      readiness: input.readiness ?? null,
      restingHr: input.restingHr ?? null,
      steps: input.steps ?? null,
      painIllness: input.painIllness,
      notes: input.notes ?? null,
    },
    history,
  )

  const { data, error } = await supabase
    .from("recovery_checkins")
    .upsert(
      {
        user_id: user.id,
        checkin_date: todayIso(),
        sleep_hours: input.sleepHours ?? null,
        sleep_quality: input.sleepQuality ?? null,
        stress: input.stress ?? null,
        fatigue: input.fatigue ?? null,
        soreness: input.soreness ?? null,
        mood: input.mood ?? null,
        readiness: input.readiness ?? null,
        resting_hr: input.restingHr ?? null,
        steps: input.steps ?? null,
        pain_illness: input.painIllness,
        notes: input.notes ?? null,
        recovery_score: result.score,
        score_breakdown: result.drivers,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "user_id,checkin_date" },
    )
    .select(
      "id, user_id, checkin_date, sleep_hours, sleep_quality, stress, fatigue, soreness, mood, readiness, resting_hr, steps, pain_illness, notes, recovery_score, score_breakdown, created_at, updated_at",
    )
    .single()

  if (error) {
    console.error("[RECOVERY CHECKIN]", error)

    return NextResponse.json(
      { error: "Unable to save your check-in. Please try again." },
      { status: 500 },
    )
  }

  return NextResponse.json({
    success: true,
    checkin: data as RecoveryCheckinRow,
    result,
  })
}
