begin;

-- =========================================================
-- 1. ADD MISSING DASHBOARD TARGETS
-- =========================================================

alter table public.fitness_profiles
  add column if not exists water_target_ml integer,
  add column if not exists step_target integer;

update public.fitness_profiles
set
  water_target_ml = coalesce(water_target_ml, 2500),
  step_target = coalesce(step_target, daily_steps, 10000)
where water_target_ml is null
   or step_target is null;

alter table public.fitness_profiles
  alter column water_target_ml set default 2500,
  alter column step_target set default 10000;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'fitness_profiles_water_target_range'
  ) then
    alter table public.fitness_profiles
      add constraint fitness_profiles_water_target_range
      check (
        water_target_ml is null
        or water_target_ml between 250 and 20000
      );
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'fitness_profiles_step_target_range'
  ) then
    alter table public.fitness_profiles
      add constraint fitness_profiles_step_target_range
      check (
        step_target is null
        or step_target between 0 and 100000
      );
  end if;
end;
$$;

-- =========================================================
-- 2. DAILY CLIENT METRICS
-- =========================================================

create table if not exists public.daily_client_metrics (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users (id)
    on delete cascade,

  metric_date date not null default current_date,

  calories_consumed integer not null default 0,
  calorie_target integer not null default 2000,

  protein_consumed_g numeric(8, 2) not null default 0,
  protein_target_g numeric(8, 2) not null default 0,

  water_consumed_ml integer not null default 0,
  water_target_ml integer not null default 2500,

  steps integer not null default 0,
  step_target integer not null default 10000,

  sleep_hours numeric(4, 1),
  sleep_quality smallint,
  energy_level smallint,
  stress_level smallint,
  soreness_level smallint,

  workout_completed boolean not null default false,

  recovery_score smallint,
  adherence_score numeric(5, 2),

  weight_kg numeric(6, 2),

  source text not null default 'manual',
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint daily_metrics_calories_check
    check (calories_consumed between 0 and 30000),

  constraint daily_metrics_calorie_target_check
    check (calorie_target between 500 and 15000),

  constraint daily_metrics_protein_check
    check (protein_consumed_g between 0 and 2000),

  constraint daily_metrics_protein_target_check
    check (protein_target_g between 0 and 2000),

  constraint daily_metrics_water_check
    check (water_consumed_ml between 0 and 50000),

  constraint daily_metrics_water_target_check
    check (water_target_ml between 250 and 20000),

  constraint daily_metrics_steps_check
    check (steps between 0 and 200000),

  constraint daily_metrics_step_target_check
    check (step_target between 0 and 100000),

  constraint daily_metrics_sleep_hours_check
    check (
      sleep_hours is null
      or sleep_hours between 0 and 24
    ),

  constraint daily_metrics_sleep_quality_check
    check (
      sleep_quality is null
      or sleep_quality between 1 and 10
    ),

  constraint daily_metrics_energy_check
    check (
      energy_level is null
      or energy_level between 1 and 10
    ),

  constraint daily_metrics_stress_check
    check (
      stress_level is null
      or stress_level between 1 and 10
    ),

  constraint daily_metrics_soreness_check
    check (
      soreness_level is null
      or soreness_level between 1 and 10
    ),

  constraint daily_metrics_recovery_check
    check (
      recovery_score is null
      or recovery_score between 0 and 100
    ),

  constraint daily_metrics_adherence_check
    check (
      adherence_score is null
      or adherence_score between 0 and 100
    ),

  constraint daily_metrics_weight_check
    check (
      weight_kg is null
      or weight_kg between 20 and 500
    ),

  constraint daily_metrics_source_length
    check (char_length(source) between 1 and 50),

  constraint daily_metrics_notes_length
    check (
      notes is null
      or char_length(notes) <= 2000
    )
);

-- Bảo đảm table cũ hoặc table tạo dở cũng có đủ columns.
alter table public.daily_client_metrics
  add column if not exists metric_date date not null default current_date,
  add column if not exists calories_consumed integer not null default 0,
  add column if not exists calorie_target integer not null default 2000,
  add column if not exists protein_consumed_g numeric(8, 2) not null default 0,
  add column if not exists protein_target_g numeric(8, 2) not null default 0,
  add column if not exists water_consumed_ml integer not null default 0,
  add column if not exists water_target_ml integer not null default 2500,
  add column if not exists steps integer not null default 0,
  add column if not exists step_target integer not null default 10000,
  add column if not exists sleep_hours numeric(4, 1),
  add column if not exists sleep_quality smallint,
  add column if not exists energy_level smallint,
  add column if not exists stress_level smallint,
  add column if not exists soreness_level smallint,
  add column if not exists workout_completed boolean not null default false,
  add column if not exists recovery_score smallint,
  add column if not exists adherence_score numeric(5, 2),
  add column if not exists weight_kg numeric(6, 2),
  add column if not exists source text not null default 'manual',
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists
  daily_client_metrics_user_date_unique
on public.daily_client_metrics (
  user_id,
  metric_date
);

create index if not exists
  daily_client_metrics_user_date_index
on public.daily_client_metrics (
  user_id,
  metric_date desc
);

-- =========================================================
-- 3. WEIGHT ENTRIES
-- =========================================================

create table if not exists public.weight_entries (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users (id)
    on delete cascade,

  measured_on date not null default current_date,

  weight_kg numeric(6, 2) not null,

  source text not null default 'manual',
  notes text,

  created_at timestamptz not null default now(),

  constraint weight_entries_weight_range
    check (weight_kg between 20 and 500),

  constraint weight_entries_source_length
    check (char_length(source) between 1 and 50),

  constraint weight_entries_notes_length
    check (
      notes is null
      or char_length(notes) <= 2000
    )
);

create unique index if not exists
  weight_entries_user_date_unique
on public.weight_entries (
  user_id,
  measured_on
);

create index if not exists
  weight_entries_user_date_index
on public.weight_entries (
  user_id,
  measured_on desc
);

-- =========================================================
-- 4. UPDATED_AT TRIGGER
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists
  daily_client_metrics_set_updated_at
on public.daily_client_metrics;

create trigger daily_client_metrics_set_updated_at
before update on public.daily_client_metrics
for each row
execute function public.set_updated_at();

-- =========================================================
-- 5. PRIVILEGES
-- =========================================================

revoke all
on table public.daily_client_metrics
from anon, authenticated;

revoke all
on table public.weight_entries
from anon, authenticated;

grant select, insert, update, delete
on table public.daily_client_metrics
to authenticated;

grant select, insert, update, delete
on table public.weight_entries
to authenticated;

-- =========================================================
-- 6. ROW LEVEL SECURITY
-- =========================================================

alter table public.daily_client_metrics
  enable row level security;

alter table public.weight_entries
  enable row level security;

drop policy if exists daily_metrics_select_own
on public.daily_client_metrics;

drop policy if exists daily_metrics_insert_own
on public.daily_client_metrics;

drop policy if exists daily_metrics_update_own
on public.daily_client_metrics;

drop policy if exists daily_metrics_delete_own
on public.daily_client_metrics;

create policy daily_metrics_select_own
on public.daily_client_metrics
for select
to authenticated
using (
  user_id = (select auth.uid())
);

create policy daily_metrics_insert_own
on public.daily_client_metrics
for insert
to authenticated
with check (
  user_id = (select auth.uid())
);

create policy daily_metrics_update_own
on public.daily_client_metrics
for update
to authenticated
using (
  user_id = (select auth.uid())
)
with check (
  user_id = (select auth.uid())
);

create policy daily_metrics_delete_own
on public.daily_client_metrics
for delete
to authenticated
using (
  user_id = (select auth.uid())
);

drop policy if exists weight_entries_select_own
on public.weight_entries;

drop policy if exists weight_entries_insert_own
on public.weight_entries;

drop policy if exists weight_entries_update_own
on public.weight_entries;

drop policy if exists weight_entries_delete_own
on public.weight_entries;

create policy weight_entries_select_own
on public.weight_entries
for select
to authenticated
using (
  user_id = (select auth.uid())
);

create policy weight_entries_insert_own
on public.weight_entries
for insert
to authenticated
with check (
  user_id = (select auth.uid())
);

create policy weight_entries_update_own
on public.weight_entries
for update
to authenticated
using (
  user_id = (select auth.uid())
)
with check (
  user_id = (select auth.uid())
);

create policy weight_entries_delete_own
on public.weight_entries
for delete
to authenticated
using (
  user_id = (select auth.uid())
);

-- =========================================================
-- 7. DASHBOARD RPC
-- =========================================================

create or replace function public.get_client_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_today date := current_date;

  v_profile jsonb;
  v_targets jsonb;
  v_today_data jsonb;
  v_weight_trend jsonb;
  v_weekly_adherence numeric;
begin
  if v_user_id is null then
    raise exception 'Authentication required'
      using errcode = '42501';
  end if;

  select jsonb_build_object(
    'userId', p.user_id,
    'fullName', p.full_name,
    'avatarUrl', p.avatar_url,
    'timezone', p.timezone,
    'onboardingCompleted', p.onboarding_completed
  )
  into v_profile
  from public.profiles as p
  where p.user_id = v_user_id;

  select jsonb_build_object(
    'goal', fp.goal,
    'currentWeightKg', fp.current_weight_kg,
    'targetWeightKg', fp.target_weight_kg,
    'calories', coalesce(fp.calorie_target, 2000),
    'proteinG', coalesce(fp.protein_target_g, 0),
    'carbsG', coalesce(fp.carb_target_g, 0),
    'fatG', coalesce(fp.fat_target_g, 0),
    'waterMl', coalesce(fp.water_target_ml, 2500),
    'steps', coalesce(fp.step_target, 10000)
  )
  into v_targets
  from public.fitness_profiles as fp
  where fp.user_id = v_user_id;

  select jsonb_build_object(
    'date', dcm.metric_date,

    'caloriesConsumed', dcm.calories_consumed,
    'calorieTarget', dcm.calorie_target,

    'proteinConsumedG', dcm.protein_consumed_g,
    'proteinTargetG', dcm.protein_target_g,

    'waterConsumedMl', dcm.water_consumed_ml,
    'waterTargetMl', dcm.water_target_ml,

    'steps', dcm.steps,
    'stepTarget', dcm.step_target,

    'sleepHours', dcm.sleep_hours,
    'sleepQuality', dcm.sleep_quality,
    'energyLevel', dcm.energy_level,
    'stressLevel', dcm.stress_level,
    'sorenessLevel', dcm.soreness_level,

    'workoutCompleted', dcm.workout_completed,

    'recoveryScore', dcm.recovery_score,
    'adherenceScore', dcm.adherence_score,

    'weightKg', dcm.weight_kg,
    'source', dcm.source
  )
  into v_today_data
  from public.daily_client_metrics as dcm
  where dcm.user_id = v_user_id
    and dcm.metric_date = v_today
  limit 1;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'date', history.measured_on,
        'weightKg', history.weight_kg
      )
      order by history.measured_on
    ),
    '[]'::jsonb
  )
  into v_weight_trend
  from (
    select
      we.measured_on,
      we.weight_kg
    from public.weight_entries as we
    where we.user_id = v_user_id
    order by we.measured_on desc
    limit 14
  ) as history;

  select coalesce(
    round(avg(dcm.adherence_score)::numeric, 1),
    0
  )
  into v_weekly_adherence
  from public.daily_client_metrics as dcm
  where dcm.user_id = v_user_id
    and dcm.metric_date between v_today - 6 and v_today;

  return jsonb_build_object(
    'profile',
    coalesce(v_profile, '{}'::jsonb),

    'targets',
    coalesce(v_targets, '{}'::jsonb),

    'today',
    coalesce(
      v_today_data,
      jsonb_build_object(
        'date', v_today,
        'caloriesConsumed', 0,
        'proteinConsumedG', 0,
        'waterConsumedMl', 0,
        'steps', 0,
        'workoutCompleted', false,
        'recoveryScore', 0,
        'adherenceScore', 0
      )
    ),

    'weightTrend',
    coalesce(v_weight_trend, '[]'::jsonb),

    'weeklyAdherence',
    coalesce(v_weekly_adherence, 0)
  );
end;
$$;

revoke all
on function public.get_client_dashboard()
from public;

grant execute
on function public.get_client_dashboard()
to authenticated;

commit;