import type { Exercise } from "./types";

export const seedExercises: Exercise[] = [
  {
    id: "ex-barbell-bench",
    name: "Barbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Lie on the bench with eyes under the bar.",
      "Unrack, lower to mid-chest with control, press up.",
    ],
    techniqueCues: [
      "Retract scapula",
      "Feet planted",
      "Wrists stacked over elbows",
    ],
    mediaUrl:
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    contraindications: ["Acute shoulder impingement", "Unhealed pec strain"],
  },
  {
    id: "ex-incline-db",
    name: "Incline Dumbbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Set bench to ~30°.",
      "Press dumbbells from chest line to lockout without clanging.",
    ],
    techniqueCues: ["Soft lockout", "Keep ribs down"],
    mediaType: "image",
    contraindications: ["Severe anterior shoulder pain"],
  },
  {
    id: "ex-cable-fly",
    name: "Cable Fly",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Set pulleys high or mid.",
      "Bring handles together in an arc with slight elbow bend.",
    ],
    techniqueCues: ["Squeeze at midline", "Control the eccentric"],
    contraindications: [],
  },
  {
    id: "ex-barbell-row",
    name: "Barbell Bent-Over Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "traps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Hinge to ~45°, pull bar to lower ribs, lower with control.",
    ],
    techniqueCues: ["Neutral spine", "Initiate with elbows"],
    mediaUrl:
      "https://images.unsplash.com/photo-1603287681836-b174ce3704ba?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    contraindications: ["Acute lumbar disc flare"],
  },
  {
    id: "ex-lat-pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Pull the bar to upper chest, lean slightly back, control up.",
    ],
    techniqueCues: ["Depress scapula first", "Avoid excessive lean"],
    contraindications: [],
  },
  {
    id: "ex-pullup",
    name: "Pull-Up",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: ["Hang from bar, pull chin over bar, lower to dead hang."],
    techniqueCues: ["Full ROM", "No kipping unless programmed"],
    contraindications: ["Acute elbow tendinopathy"],
  },
  {
    id: "ex-ohp",
    name: "Overhead Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps", "traps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Press bar from front rack to lockout overhead, lower to collarbone.",
    ],
    techniqueCues: ["Glutes tight", "Head through at lockout"],
    contraindications: ["Uncontrolled hypertension", "Acute shoulder injury"],
  },
  {
    id: "ex-lateral-raise",
    name: "Dumbbell Lateral Raise",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: ["Raise dumbbells to just below shoulder height, lower slow."],
    techniqueCues: ["Lead with elbows", "Slight bend only"],
    contraindications: [],
  },
  {
    id: "ex-squat",
    name: "Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core", "hamstrings"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Bar on upper traps, brace, sit between hips, drive up.",
    ],
    techniqueCues: ["Knees track toes", "Depth consistent"],
    mediaUrl:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
    mediaType: "image",
    contraindications: ["Acute knee swelling", "Unstable lumbar injury"],
  },
  {
    id: "ex-rdl",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Soft knees, hinge until hamstrings load, return standing.",
    ],
    techniqueCues: ["Bar close to legs", "Neutral neck"],
    contraindications: ["Acute hamstring tear"],
  },
  {
    id: "ex-leg-press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Feet mid-platform, lower until knees ~90°, press without locking violently.",
    ],
    techniqueCues: ["Do not let hips tuck under", "Full foot contact"],
    contraindications: [],
  },
  {
    id: "ex-hip-thrust",
    name: "Barbell Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: [
      "Upper back on bench, bar over hips, drive to full hip extension.",
    ],
    techniqueCues: ["Chin tucked", "Pause at top"],
    contraindications: [],
  },
  {
    id: "ex-curl",
    name: "Dumbbell Biceps Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: ["Curl without swinging, squeeze at top, lower fully."],
    techniqueCues: ["Elbows pinned", "Supinate through the range"],
    contraindications: [],
  },
  {
    id: "ex-triceps-pushdown",
    name: "Triceps Pushdown",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    instructions: ["Push attachment down to lockout, control return."],
    techniqueCues: ["Ribs down", "Only elbows move"],
    contraindications: [],
  },
  {
    id: "ex-plank",
    name: "Front Plank",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: [
      "Hold a straight line from head to heels; log duration as reps in seconds.",
    ],
    techniqueCues: ["Glutes on", "Neutral neck"],
    contraindications: ["Acute low-back extension intolerance — modify"],
  },
  {
    id: "ex-calf-raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: ["Full stretch at bottom, rise onto balls of feet, pause."],
    techniqueCues: ["Control both ends of ROM"],
    contraindications: ["Acute Achilles tendinopathy"],
  },
];

export function createDefaultPlan() {
  const now = new Date().toISOString();
  return {
    id: "plan-push-pull-legs",
    name: "Push / Pull / Legs",
    description:
      "3-day strength split. Duplicate days or edit sets in the plan builder.",
    createdAt: now,
    updatedAt: now,
    days: [
      {
        id: "day-push",
        name: "Push",
        order: 0,
        exercises: [
          {
            id: "pe-1",
            exerciseId: "ex-barbell-bench",
            order: 0,
            sets: 4,
            repMin: 5,
            repMax: 8,
            targetRir: 2,
            restSeconds: 150,
            tempo: "3-0-1-0",
            coachNotes: "Leave 1–2 reps in reserve on last set.",
          },
          {
            id: "pe-2",
            exerciseId: "ex-ohp",
            order: 1,
            sets: 3,
            repMin: 6,
            repMax: 10,
            targetRir: 2,
            restSeconds: 120,
            tempo: "2-0-1-0",
          },
          {
            id: "pe-3",
            exerciseId: "ex-incline-db",
            order: 2,
            sets: 3,
            repMin: 8,
            repMax: 12,
            targetRir: 2,
            restSeconds: 90,
          },
          {
            id: "pe-4",
            exerciseId: "ex-lateral-raise",
            order: 3,
            sets: 3,
            repMin: 12,
            repMax: 15,
            targetRir: 1,
            restSeconds: 60,
          },
          {
            id: "pe-5",
            exerciseId: "ex-triceps-pushdown",
            order: 4,
            sets: 3,
            repMin: 10,
            repMax: 15,
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        id: "day-pull",
        name: "Pull",
        order: 1,
        exercises: [
          {
            id: "pe-6",
            exerciseId: "ex-barbell-row",
            order: 0,
            sets: 4,
            repMin: 6,
            repMax: 10,
            targetRir: 2,
            restSeconds: 120,
          },
          {
            id: "pe-7",
            exerciseId: "ex-lat-pulldown",
            order: 1,
            sets: 3,
            repMin: 8,
            repMax: 12,
            targetRir: 2,
            restSeconds: 90,
          },
          {
            id: "pe-8",
            exerciseId: "ex-pullup",
            order: 2,
            sets: 3,
            repMin: 5,
            repMax: 8,
            targetRir: 2,
            restSeconds: 120,
            coachNotes: "Use band assist if needed.",
          },
          {
            id: "pe-9",
            exerciseId: "ex-curl",
            order: 3,
            sets: 3,
            repMin: 10,
            repMax: 15,
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        id: "day-legs",
        name: "Legs",
        order: 2,
        exercises: [
          {
            id: "pe-10",
            exerciseId: "ex-squat",
            order: 0,
            sets: 4,
            repMin: 5,
            repMax: 8,
            targetRir: 2,
            restSeconds: 180,
            tempo: "3-1-1-0",
          },
          {
            id: "pe-11",
            exerciseId: "ex-rdl",
            order: 1,
            sets: 3,
            repMin: 6,
            repMax: 10,
            targetRir: 2,
            restSeconds: 120,
          },
          {
            id: "pe-12",
            exerciseId: "ex-leg-press",
            order: 2,
            sets: 3,
            repMin: 10,
            repMax: 15,
            targetRir: 2,
            restSeconds: 90,
          },
          {
            id: "pe-13",
            exerciseId: "ex-hip-thrust",
            order: 3,
            sets: 3,
            repMin: 8,
            repMax: 12,
            targetRir: 2,
            restSeconds: 90,
          },
          {
            id: "pe-14",
            exerciseId: "ex-calf-raise",
            order: 4,
            sets: 3,
            repMin: 12,
            repMax: 20,
            targetRir: 1,
            restSeconds: 60,
          },
          {
            id: "pe-15",
            exerciseId: "ex-plank",
            order: 5,
            sets: 3,
            repMin: 30,
            repMax: 60,
            targetRir: 1,
            restSeconds: 45,
            coachNotes: "Log hold time as reps (seconds).",
          },
        ],
      },
    ],
  };
}
